name: Dotnet CI

on: 
    push: 
        branches: 
            - main
        paths: 
            - 'src/**'
    pull_request: 
        branches: 
            - main
        paths: 
            - 'src/**'

jobs:
    build-and-test-dotnet:
        name: Build & Test .NET App
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./src
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '9.0.x'

            - name: Resotre dependencies
              run: dotnet Resotre
            - name: Build application
              run: dotnet build --configuration release --no-Resotre
            - name: Run automated tests
              run: dotnet test --configuration Release --no-Resotre --no-build
              